site_name: Meu Projeto
docs_dir: docs/
theme:
  name: material

nav:
  - Início: index.md
  - HTML:
      - Introdução: html/introducao/index.md
      - Estrutura Base: html/estrutura-base/index.md
      - Elementos Iniciais: html/elementos-iniciais/index.md
      - Elementos Avançados: html/elementos-avancados/index.md
  - CSS: css/index.md
  - JavaScript: js/index.md
  - TypeScript: ts/index.md
  - Angular: angular/index.md
