site_name: HowTo.Dev
docs_dir: docs/
theme:
  name: material

markdown_extensions:
  - markdown_include.include:
      base_path: assets
nav:
  - Início: index.md
  - HTML:
      - Introdução: html/index.md
      - Estrutura Base:
          - HTML: html/estrutura-base/html.md
          - Head: html/estrutura-base/head.md
          - Body: html/estrutura-base/body.md
      - Elementos:
          - Head:
              - Título: html/elementos/head/title.md
          - Body:
              - Heading (Textos): html/elementos/body/hn.md
              - Divisor: html/elementos/body/div.md
              - Textos e Intervalo: html/elementos/body/p-span.md
              - Estilizando Textos: html/elementos/body/estilos-textos.md
              - Pular Linha: html/elementos/body/br.md
              - Lista Não Ordenada: html/elementos/body/ul.md
              - Lista Ordenada: html/elementos/body/ol.md
              - Imagem: html/elementos/body/img.md
              - Video: html/elementos/body/video.md
              - Link:
                  - Outra Página: html/elementos/body/a/outra-pagina.md
                  - Página Relativa: html/elementos/body/a/pagina-relativa.md
                  - Outros Elementos: html/elementos/body/a/outros-elementos.md
                  - Item da Página: html/elementos/body/a/item-pagina.md
              - Tabela:
                  - Simples: html/elementos/body/table/intro.md
                  - Muitos Dados: html/elementos/body/table/muitos-dados.md
              - Formulário:
                  - Introdução: html/elementos/body/form/intro.md
                  - Input: html/elementos/body/form/input.md
                  - Select: html/elementos/body/form/select.md
                  - TextArea: html/elementos/body/form/textarea.md
                  - Botão Enviar: html/elementos/body/form/submit.md
                  - Validações:
                      - Introdução: html/elementos/body/form/validations/intro.md
                      - Required (Obrigatório): html/elementos/body/form/validations/required.md
                      - Min-Max (Mínimo e Máximo): html/elementos/body/form/validations/min-max.md
                      - Length (Tamanho): html/elementos/body/form/validations/length.md
                      - Pattern (Máscara): html/elementos/body/form/validations/pattern.md
          - Atributos: html/elementos/atributos/index.md
          - RegEx: html/elementos/body/form/validations/regex.md
      - Semantica:
          - Introdução: html/semantica/intro.md
          - Header e Nav: html/semantica/header-nav.md
          - Main e Footer: html/semantica/main-footer.md
          - Article e Section: html/semantica/article-section.md
          - Aside: html/semantica/aside.md
          - Figure e Figcaption: html/semantica/figure-figcaption.md
          - Audio e Attributes: html/semantica/audio-attributes.md
          - Video e Embed: html/semantica/video-embed.md
  - CSS:
      - Introdução: css/index.md
      - Sintaxe Basica:
          - Estilo em Linha: css/sintaxe-base/estilo-linha.md
          - Folha de Estilo: css/sintaxe-base/folha-estilo.md
          - Folha de Estilo Externa: css/sintaxe-base/folha-estilo-externa.md
          - Linkar Estilo: css/sintaxe-base/link-estilo.md
      - Seletores:
          - Tipo: css/seletores/tipo.md
          - Universal: css/seletores/universal.md
          - Classe: css/seletores/classe.md
          - Multiplas Classes: css/seletores/multi-classes.md
          - Id: css/seletores/id.md
          - Pseudo Classe: css/seletores/pseudo-classe.md
          - Especificidade: css/seletores/especificidade.md
          - Encadeamento: css/seletores/encadeamento.md
          - Descendentes: css/seletores/descendentes.md
          - Encadeamento e Especificidade: css/seletores/encadeamento-especificidade.md
          - Multiplos Seletores: css/seletores/multi-seletores.md
  - JavaScript: js/index.md
  - TypeScript: ts/index.md
  - Angular: angular/index.md
