site_name: HowTo.Dev
docs_dir: docs/
theme:
  name: material

nav:
  - Início: index.md
  - HTML:
      - Introdução: html/introducao/index.md
      - Estrutura Base:
          - HTML: html/estrutura-base/html/index.md
          - Head: html/estrutura-base/head/index.md
          - Body: html/estrutura-base/body/index.md
      - Elementos Iniciais:
          - Head:
              - Título: html/elementos-iniciais/head/title/index.md
          - Body:
              - Heading (Textos): html/elementos-iniciais/body/hn/index.md
              - Divisor: html/elementos-iniciais/body/div/index.md
              - Textos e Intervalo: html/elementos-iniciais/body/p-span/index.md
              - Estilizando Textos: html/elementos-iniciais/body/estilos-textos/index.md
              - Pular Linha: html/elementos-iniciais/body/br/index.md
              - Lista Não Ordenada: html/elementos-iniciais/body/ul/index.md
              - Lista Ordenada: html/elementos-iniciais/body/ol/index.md
              - Imagem: html/elementos-iniciais/body/img/index.md
              - Video: html/elementos-iniciais/body/video/index.md
              - Link:
                  - Outra Página: html/elementos-iniciais/body/a/outra-pagina/index.md
                  - Página Relativa: html/elementos-iniciais/body/a/pagina-relativa/index.md
                  - Outros Elementos: html/elementos-iniciais/body/a/outros-elementos/index.md
                  - Item da Página: html/elementos-iniciais/body/a/item-pagina/index.md
      - Elementos Avançados:
          - Body:
              - Tabela:
                  - Simples: html/elementos-avancados/body/table/intro/index.md
                  - Muitos Dados: html/elementos-avancados/body/table/muitos-dados/index.md
              - Formulário:
                  - Introdução: html/elementos-avancados/body/form/intro/index.md
                  - Input: html/elementos-avancados/body/form/input/index.md
  - CSS: css/index.md
  - JavaScript: js/index.md
  - TypeScript: ts/index.md
  - Angular: angular/index.md
